services:
  backend: 
    build: .
    container_name: testease_backend
    restart: always
    ports:
      - "8000:8000"
    # volumes:
    #   - .:/app
    env_file:
      - .env
    depends_on:
      - redis
  
  redis:
    image: "redis:7-alpine"
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
